services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: semantic_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: semanticdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: semantic_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ollama-pull-models:
    image: ollama/ollama
    container_name: ollama_pull_models
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: /bin/sh
    command: -c "sleep 5; ollama pull nomic-embed-text; ollama pull gemma3:1b"
    depends_on:
      - ollama

  pgadmin:
    image: dpage/pgadmin4
    container_name: semantic_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
  ollama_data: