@src_HostAddress = http://localhost:5162

POST {{src_HostAddress}}/api/Ingestion/run
Content-Type: application/json

{}

###

POST {{src_HostAddress}}/api/Search
Content-Type: application/json

{
  "query": "lighthouse",
  "limit": 5
}